logging:
  level:
    me.acomma.admin.data.mapper: debug
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/admin?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
